#include "theme.h"

Theme Theme::make(const QString &name) {
    Theme t;
    if (name == QStringLiteral("light")) {
        t.background = QColor("#f5f6f8");
        t.cursor_line = QColor("#d0d8e0");
        t.highlight = QColor("#c8d8e8");
        t.empty_text = QColor("#7a8288");
        t.status_ok = QColor("#1a7f37");
        t.status_error = QColor("#c0392b");
        t.job_running = QColor("#9a6700");
        t.job_cancelled = QColor("#7a8288");
        t.address_column = QColor("#0550ae");
        t.bytes_column = QColor("#57606a");
        t.mnemonic = QColor("#8250df");
        t.operands = QColor("#1f2328");
        t.jump_target = QColor("#0969da");
        t.variable = QColor("#953800");
        t.function_name = QColor("#0550ae");
        t.operator_ = QColor("#0969da");
        t.keyword = QColor("#8250df");
        t.node_fill = QColor("#eaeef2");
        t.node_border = QColor("#0550ae");
        t.node_highlight = QColor("#9a6700");
        t.node_text = QColor("#1f2328");
        t.edge_true = QColor("#1a7f37");
        t.edge_false = QColor("#c0392b");
        t.edge_unconditional = QColor("#57606a");
        t.edge_call = QColor("#8250df");
        t.offset_column = QColor("#0550ae");
        t.hex_text = QColor("#1f2328");
        t.ascii_text = QColor("#57606a");
        t.pointer = QColor("#0969da");
        return t;
    }
    if (name == QStringLiteral("contrast")) {
        t.background = QColor("#000000");
        t.cursor_line = QColor("#3a3a3a");
        t.highlight = QColor("#4a4a00");
        t.empty_text = QColor("#a0a0a0");
        t.status_ok = QColor("#00ff00");
        t.status_error = QColor("#ff4040");
        t.job_running = QColor("#ffff00");
        t.job_cancelled = QColor("#a0a0a0");
        t.address_column = QColor("#00ffff");
        t.bytes_column = QColor("#c0c0c0");
        t.mnemonic = QColor("#ff80ff");
        t.operands = QColor("#ffffff");
        t.jump_target = QColor("#00ffff");
        t.variable = QColor("#ffff80");
        t.function_name = QColor("#80ffff");
        t.operator_ = QColor("#00ff80");
        t.keyword = QColor("#ff80ff");
        t.node_fill = QColor("#202020");
        t.node_border = QColor("#00ffff");
        t.node_highlight = QColor("#ffff00");
        t.node_text = QColor("#ffffff");
        t.edge_true = QColor("#00ff00");
        t.edge_false = QColor("#ff4040");
        t.edge_unconditional = QColor("#c0c0c0");
        t.edge_call = QColor("#ff80ff");
        t.offset_column = QColor("#00ffff");
        t.hex_text = QColor("#ffffff");
        t.ascii_text = QColor("#c0c0c0");
        t.pointer = QColor("#00ffff");
        return t;
    }
    // Dark (default).
    t.background = QColor("#101419");
    t.cursor_line = QColor("#2a3542");
    t.highlight = QColor("#3a4a5a");
    t.empty_text = QColor("#7e8996");
    t.status_ok = QColor("#98c379");
    t.status_error = QColor("#e06c75");
    t.job_running = QColor("#e5c07b");
    t.job_cancelled = QColor("#7e8996");
    t.address_column = QColor("#79b8ff");
    t.bytes_column = QColor("#8fa8bf");
    t.mnemonic = QColor("#c678dd");
    t.operands = QColor("#d6dee8");
    t.jump_target = QColor("#56b6c2");
    t.variable = QColor("#e5c07b");
    t.function_name = QColor("#61afef");
    t.operator_ = QColor("#56b6c2");
    t.keyword = QColor("#c678dd");
    t.node_fill = QColor("#202a35");
    t.node_border = QColor("#79b8ff");
    t.node_highlight = QColor("#e5c07b");
    t.node_text = QColor("#d6dee8");
    t.edge_true = QColor("#98c379");
    t.edge_false = QColor("#e06c75");
    t.edge_unconditional = QColor("#56606d");
    t.edge_call = QColor("#c678dd");
    t.offset_column = QColor("#79b8ff");
    t.hex_text = QColor("#d6dee8");
    t.ascii_text = QColor("#8fa8bf");
    t.pointer = QColor("#56b6c2");
    return t;
}
