/* Generated By:JavaCC: Do not edit this line. CParserConstants.java */
package ghidra.app.util.cparser.C;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 10;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 11;
  /** RegularExpression Id. */
  int HEX_LITERAL = 12;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 13;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 14;
  /** RegularExpression Id. */
  int EXPONENT = 15;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 16;
  /** RegularExpression Id. */
  int STRING_LITERAL = 17;
  /** RegularExpression Id. */
  int CONTINUE = 18;
  /** RegularExpression Id. */
  int VOLATILE = 19;
  /** RegularExpression Id. */
  int REGISTER = 20;
  /** RegularExpression Id. */
  int UNSIGNED = 21;
  /** RegularExpression Id. */
  int TYPEDEF = 22;
  /** RegularExpression Id. */
  int DFLT = 23;
  /** RegularExpression Id. */
  int DOUBLE = 24;
  /** RegularExpression Id. */
  int SIZEOF = 25;
  /** RegularExpression Id. */
  int SWITCH = 26;
  /** RegularExpression Id. */
  int RETURN = 27;
  /** RegularExpression Id. */
  int EXTERN = 28;
  /** RegularExpression Id. */
  int QUOTE_C = 29;
  /** RegularExpression Id. */
  int STRUCT = 30;
  /** RegularExpression Id. */
  int STATIC = 31;
  /** RegularExpression Id. */
  int THREADLOCAL = 32;
  /** RegularExpression Id. */
  int SIGNED = 33;
  /** RegularExpression Id. */
  int WHILE = 34;
  /** RegularExpression Id. */
  int BREAK = 35;
  /** RegularExpression Id. */
  int UNION = 36;
  /** RegularExpression Id. */
  int CONST = 37;
  /** RegularExpression Id. */
  int DECLSPEC = 38;
  /** RegularExpression Id. */
  int PRAGMA = 39;
  /** RegularExpression Id. */
  int PRAGMA_FUNC = 40;
  /** RegularExpression Id. */
  int READABLETO = 41;
  /** RegularExpression Id. */
  int CDECL = 42;
  /** RegularExpression Id. */
  int STDCALL = 43;
  /** RegularExpression Id. */
  int FASTCALL = 44;
  /** RegularExpression Id. */
  int VECTORCALL = 45;
  /** RegularExpression Id. */
  int RUSTCALL = 46;
  /** RegularExpression Id. */
  int PASCALCALL = 47;
  /** RegularExpression Id. */
  int NORETURN = 48;
  /** RegularExpression Id. */
  int ALIGNAS = 49;
  /** RegularExpression Id. */
  int ALIGNOF = 50;
  /** RegularExpression Id. */
  int UNALIGNED = 51;
  /** RegularExpression Id. */
  int PACKED = 52;
  /** RegularExpression Id. */
  int ATTRIBUTE = 53;
  /** RegularExpression Id. */
  int EXTENSION = 54;
  /** RegularExpression Id. */
  int RESTRICT = 55;
  /** RegularExpression Id. */
  int ASM = 56;
  /** RegularExpression Id. */
  int INLINE = 57;
  /** RegularExpression Id. */
  int STATICASSERT = 58;
  /** RegularExpression Id. */
  int FLOAT = 59;
  /** RegularExpression Id. */
  int SHORT = 60;
  /** RegularExpression Id. */
  int ELSE = 61;
  /** RegularExpression Id. */
  int CASE = 62;
  /** RegularExpression Id. */
  int LONG = 63;
  /** RegularExpression Id. */
  int INT8 = 64;
  /** RegularExpression Id. */
  int INT16 = 65;
  /** RegularExpression Id. */
  int INT32 = 66;
  /** RegularExpression Id. */
  int INT64 = 67;
  /** RegularExpression Id. */
  int PTR64 = 68;
  /** RegularExpression Id. */
  int PTR32 = 69;
  /** RegularExpression Id. */
  int BOOL = 70;
  /** RegularExpression Id. */
  int W64 = 71;
  /** RegularExpression Id. */
  int ENUM = 72;
  /** RegularExpression Id. */
  int AUTO = 73;
  /** RegularExpression Id. */
  int VOID = 74;
  /** RegularExpression Id. */
  int CHAR = 75;
  /** RegularExpression Id. */
  int GOTO = 76;
  /** RegularExpression Id. */
  int NEAR = 77;
  /** RegularExpression Id. */
  int FAR = 78;
  /** RegularExpression Id. */
  int FOR = 79;
  /** RegularExpression Id. */
  int INT = 80;
  /** RegularExpression Id. */
  int IF = 81;
  /** RegularExpression Id. */
  int DO = 82;
  /** RegularExpression Id. */
  int PROTOCOL = 83;
  /** RegularExpression Id. */
  int INTERFACE = 84;
  /** RegularExpression Id. */
  int LINE = 85;
  /** RegularExpression Id. */
  int LINEALT = 86;
  /** RegularExpression Id. */
  int IDENTIFIER = 87;
  /** RegularExpression Id. */
  int LETTER = 88;
  /** RegularExpression Id. */
  int DIGIT = 89;
  /** RegularExpression Id. */
  int ASMBLOCKB = 92;
  /** RegularExpression Id. */
  int ASMBLOCKP = 93;
  /** RegularExpression Id. */
  int ASM_SEMI = 94;
  /** RegularExpression Id. */
  int PATH_LITERAL = 99;
  /** RegularExpression Id. */
  int LINENUMBER_LITERAL = 100;
  /** RegularExpression Id. */
  int PIDENTIFIER = 109;
  /** RegularExpression Id. */
  int PLETTER = 110;
  /** RegularExpression Id. */
  int PDIGIT = 111;
  /** RegularExpression Id. */
  int POPEN = 112;
  /** RegularExpression Id. */
  int PCLOSE = 113;
  /** RegularExpression Id. */
  int PMINUS = 114;
  /** RegularExpression Id. */
  int PPLUS = 115;
  /** RegularExpression Id. */
  int PSTAR = 116;
  /** RegularExpression Id. */
  int PCOLON = 117;
  /** RegularExpression Id. */
  int PCOMMA = 118;
  /** RegularExpression Id. */
  int PINTEGER_LITERAL = 119;
  /** RegularExpression Id. */
  int PDECIMAL_LITERAL = 120;
  /** RegularExpression Id. */
  int PHEX_LITERAL = 121;
  /** RegularExpression Id. */
  int POCTAL_LITERAL = 122;
  /** RegularExpression Id. */
  int PSTRING_LITERAL = 123;
  /** RegularExpression Id. */
  int OBJC_IGNORE = 129;
  /** RegularExpression Id. */
  int OBJC_IDENTIFIER = 130;
  /** RegularExpression Id. */
  int OBJC_LETTER = 131;
  /** RegularExpression Id. */
  int OBJC_DIGIT = 132;
  /** RegularExpression Id. */
  int OBJC_SEMI = 133;
  /** RegularExpression Id. */
  int OBJC2_IGNORE = 144;
  /** RegularExpression Id. */
  int OBJC2_END = 145;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ASMBLOCK = 1;
  /** Lexical state. */
  int LINEBLOCK = 2;
  /** Lexical state. */
  int PRAGMALINE = 3;
  /** Lexical state. */
  int OBJC = 4;
  /** Lexical state. */
  int OBJC2 = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\ufeff\"",
    "\" \"",
    "\"\\f\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\\\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"continue\"",
    "<VOLATILE>",
    "\"register\"",
    "\"unsigned\"",
    "\"typedef\"",
    "\"default\"",
    "\"double\"",
    "\"sizeof\"",
    "\"switch\"",
    "\"return\"",
    "\"extern\"",
    "\"\\\"C\\\"\"",
    "\"struct\"",
    "\"static\"",
    "\"_Thread_local\"",
    "<SIGNED>",
    "\"while\"",
    "\"break\"",
    "\"union\"",
    "<CONST>",
    "\"__declspec\"",
    "<PRAGMA>",
    "<PRAGMA_FUNC>",
    "\"__readableTo\"",
    "<CDECL>",
    "<STDCALL>",
    "<FASTCALL>",
    "<VECTORCALL>",
    "<RUSTCALL>",
    "<PASCALCALL>",
    "\"_Noreturn\"",
    "\"_Alignas\"",
    "\"_Alignof\"",
    "\"__unaligned\"",
    "\"__packed\"",
    "<ATTRIBUTE>",
    "<EXTENSION>",
    "<RESTRICT>",
    "<ASM>",
    "<INLINE>",
    "<STATICASSERT>",
    "\"float\"",
    "\"short\"",
    "\"else\"",
    "\"case\"",
    "\"long\"",
    "\"__int8\"",
    "\"__int16\"",
    "\"__int32\"",
    "\"__int64\"",
    "\"__ptr64\"",
    "\"__ptr32\"",
    "\"_Bool\"",
    "\"__w64\"",
    "\"enum\"",
    "\"auto\"",
    "\"void\"",
    "\"char\"",
    "\"goto\"",
    "\"__near\"",
    "\"__far\"",
    "\"for\"",
    "\"int\"",
    "\"if\"",
    "\"do\"",
    "\"@protocol\"",
    "\"@interface\"",
    "\"#line\"",
    "<LINEALT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\" \"",
    "\"\\t\"",
    "<ASMBLOCKB>",
    "<ASMBLOCKP>",
    "<ASM_SEMI>",
    "\" \"",
    "\"\\f\"",
    "\"\\t\"",
    "\":\"",
    "<PATH_LITERAL>",
    "<LINENUMBER_LITERAL>",
    "\" \"",
    "\"\\f\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "<token of kind 107>",
    "<token of kind 108>",
    "<PIDENTIFIER>",
    "<PLETTER>",
    "<PDIGIT>",
    "\"(\"",
    "\")\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\":\"",
    "\",\"",
    "<PINTEGER_LITERAL>",
    "<PDECIMAL_LITERAL>",
    "<PHEX_LITERAL>",
    "<POCTAL_LITERAL>",
    "<PSTRING_LITERAL>",
    "\" \"",
    "\"\\f\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<OBJC_IGNORE>",
    "<OBJC_IDENTIFIER>",
    "<OBJC_LETTER>",
    "<OBJC_DIGIT>",
    "<OBJC_SEMI>",
    "\" \"",
    "\"\\f\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"@private\"",
    "\"@protected\"",
    "\"@property\"",
    "\"@optional\"",
    "\"@required\"",
    "<OBJC2_IGNORE>",
    "\"@end\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "\"=\"",
    "\"#\"",
    "\"*\"",
    "\"&\"",
    "\"...\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"?\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\"->\"",
  };

}
