[package]
name = "ventris-decompiler"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description = "Dependency-free native decompiler for Ventris"

[dependencies]
ventris-lifter = { path = "../ventris-lifter", version = "0.3.0" }
ventris-pcode = { path = "../ventris-pcode", version = "0.3.0" }
ventris-target = { path = "../ventris-target", version = "0.3.0" }
