 [package]
 name = "ventris-cli"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "Ventris binary-analysis command-line interface"

[[bin]]
name = "ventris"
path = "src/main.rs"

[dependencies]
ventris = { path = "../ventris", version = "0.1.0" }
ventris-addr = { path = "../ventris-addr", version = "0.1.0" }
ventris-decompiler = { path = "../ventris-decompiler", version = "0.1.0" }
ventris-format = { path = "../ventris-format", version = "0.1.0" }
ventris-lifter = { path = "../ventris-lifter", version = "0.1.0" }
ventris-game = { path = "../ventris-game", version = "0.1.0" }
ventris-pcode = { path = "../ventris-pcode", version = "0.1.0" }
ventris-db = { path = "../ventris-db", version = "0.1.0" }
ventris-target = { path = "../ventris-target", version = "0.1.0" }
ventris-gen = { path = "../ventris-gen", version = "0.1.0" }
