/* Generated By:JavaCC: Do not edit this line. PreProcessorConstants.java */
package ghidra.app.util.cparser.CPP;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PreProcessorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int _BOM = 1;
  /** RegularExpression Id. */
  int _CTRL = 2;
  /** RegularExpression Id. */
  int _XSYM = 3;
  /** RegularExpression Id. */
  int _BLANKLINE = 4;
  /** RegularExpression Id. */
  int _LCMT = 5;
  /** RegularExpression Id. */
  int _CMT = 6;
  /** RegularExpression Id. */
  int EOLCMNTNL = 7;
  /** RegularExpression Id. */
  int CMNTNL = 9;
  /** RegularExpression Id. */
  int _EQ = 11;
  /** RegularExpression Id. */
  int _NEQ = 12;
  /** RegularExpression Id. */
  int _LT = 13;
  /** RegularExpression Id. */
  int _GT = 14;
  /** RegularExpression Id. */
  int _LE = 15;
  /** RegularExpression Id. */
  int _GE = 16;
  /** RegularExpression Id. */
  int _AND = 17;
  /** RegularExpression Id. */
  int _LOG_AND = 18;
  /** RegularExpression Id. */
  int _OR = 19;
  /** RegularExpression Id. */
  int _XOR = 20;
  /** RegularExpression Id. */
  int _LOG_OR = 21;
  /** RegularExpression Id. */
  int _LSH = 22;
  /** RegularExpression Id. */
  int _RSH = 23;
  /** RegularExpression Id. */
  int _MINUS = 24;
  /** RegularExpression Id. */
  int _PERCENT = 25;
  /** RegularExpression Id. */
  int _PLUS = 26;
  /** RegularExpression Id. */
  int _QMARK = 27;
  /** RegularExpression Id. */
  int _COLON = 28;
  /** RegularExpression Id. */
  int DIR = 29;
  /** RegularExpression Id. */
  int XSYM = 30;
  /** RegularExpression Id. */
  int CMT = 31;
  /** RegularExpression Id. */
  int ECMT = 32;
  /** RegularExpression Id. */
  int ENDCMT = 33;
  /** RegularExpression Id. */
  int STARTCMT = 34;
  /** RegularExpression Id. */
  int COD = 35;
  /** RegularExpression Id. */
  int ENDL = 36;
  /** RegularExpression Id. */
  int UNDIR = 37;
  /** RegularExpression Id. */
  int UNDIRALL = 38;
  /** RegularExpression Id. */
  int DEFD = 39;
  /** RegularExpression Id. */
  int OPTD = 40;
  /** RegularExpression Id. */
  int ENDREL = 41;
  /** RegularExpression Id. */
  int CP = 42;
  /** RegularExpression Id. */
  int OP = 43;
  /** RegularExpression Id. */
  int NOPAR = 44;
  /** RegularExpression Id. */
  int WSP = 45;
  /** RegularExpression Id. */
  int STD = 46;
  /** RegularExpression Id. */
  int REL = 47;
  /** RegularExpression Id. */
  int NOTENDL = 48;
  /** RegularExpression Id. */
  int NOTENDLC = 49;
  /** RegularExpression Id. */
  int NOTENDLSTAR = 50;
  /** RegularExpression Id. */
  int NOTCMT = 51;
  /** RegularExpression Id. */
  int NOTCMTCOD = 52;
  /** RegularExpression Id. */
  int NOTWS = 53;
  /** RegularExpression Id. */
  int NOTWSQ = 54;
  /** RegularExpression Id. */
  int NOTWQC = 55;
  /** RegularExpression Id. */
  int NOTWWSQLT = 56;
  /** RegularExpression Id. */
  int NOTWSQLT = 57;
  /** RegularExpression Id. */
  int NOTVALCMT = 58;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 59;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 60;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 61;
  /** RegularExpression Id. */
  int HEX_LITERAL = 62;
  /** RegularExpression Id. */
  int HEX_DIGIT = 63;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 64;
  /** RegularExpression Id. */
  int FP_LITERAL = 65;
  /** RegularExpression Id. */
  int EXPONENT = 66;
  /** RegularExpression Id. */
  int NOTCHR = 67;
  /** RegularExpression Id. */
  int WS = 68;
  /** RegularExpression Id. */
  int OUTER_TEXT = 69;
  /** RegularExpression Id. */
  int NEWLINE = 70;
  /** RegularExpression Id. */
  int OTHER_TEXT = 71;
  /** RegularExpression Id. */
  int QUOTED_TEXT = 72;
  /** RegularExpression Id. */
  int _WSP0 = 83;
  /** RegularExpression Id. */
  int _COD1 = 84;
  /** RegularExpression Id. */
  int _WSP2 = 85;
  /** RegularExpression Id. */
  int COMMA = 86;
  /** RegularExpression Id. */
  int _LCMT0 = 87;
  /** RegularExpression Id. */
  int _CMT0 = 88;
  /** RegularExpression Id. */
  int IF = 89;
  /** RegularExpression Id. */
  int ELIF = 90;
  /** RegularExpression Id. */
  int ELSE = 91;
  /** RegularExpression Id. */
  int ENDIF = 92;
  /** RegularExpression Id. */
  int IFDEFED = 93;
  /** RegularExpression Id. */
  int IFNDEFED = 94;
  /** RegularExpression Id. */
  int NOT = 95;
  /** RegularExpression Id. */
  int DEFINED = 96;
  /** RegularExpression Id. */
  int HASINCLUDE = 97;
  /** RegularExpression Id. */
  int HASINCLUDENEXT = 98;
  /** RegularExpression Id. */
  int OPTIONED = 99;
  /** RegularExpression Id. */
  int EQ = 100;
  /** RegularExpression Id. */
  int NEQ = 101;
  /** RegularExpression Id. */
  int LT = 102;
  /** RegularExpression Id. */
  int GT = 103;
  /** RegularExpression Id. */
  int LE = 104;
  /** RegularExpression Id. */
  int GE = 105;
  /** RegularExpression Id. */
  int AND = 106;
  /** RegularExpression Id. */
  int OR = 107;
  /** RegularExpression Id. */
  int XOR = 108;
  /** RegularExpression Id. */
  int LOG_OR = 109;
  /** RegularExpression Id. */
  int LOG_AND = 110;
  /** RegularExpression Id. */
  int LSH = 111;
  /** RegularExpression Id. */
  int RSH = 112;
  /** RegularExpression Id. */
  int MINUS = 113;
  /** RegularExpression Id. */
  int PLUS = 114;
  /** RegularExpression Id. */
  int DIVIDE = 115;
  /** RegularExpression Id. */
  int MOD = 116;
  /** RegularExpression Id. */
  int TIMES = 117;
  /** RegularExpression Id. */
  int QMARK = 118;
  /** RegularExpression Id. */
  int COLON = 119;
  /** RegularExpression Id. */
  int NUMERIC = 120;
  /** RegularExpression Id. */
  int FP_NUMERIC = 121;
  /** RegularExpression Id. */
  int CHAR_NUMERIC = 122;
  /** RegularExpression Id. */
  int ITEM = 123;
  /** RegularExpression Id. */
  int BEGITEM = 124;
  /** RegularExpression Id. */
  int ENDITEM = 125;
  /** RegularExpression Id. */
  int DIRLINE = 126;
  /** RegularExpression Id. */
  int _TOEOL = 127;
  /** RegularExpression Id. */
  int _LCMT11 = 128;
  /** RegularExpression Id. */
  int _CMT11 = 129;
  /** RegularExpression Id. */
  int _INCCOD = 130;
  /** RegularExpression Id. */
  int _INCWSP = 131;
  /** RegularExpression Id. */
  int _INCCP = 132;
  /** RegularExpression Id. */
  int _INCOP = 133;
  /** RegularExpression Id. */
  int _INCSTANDARD = 134;
  /** RegularExpression Id. */
  int _HEX = 135;
  /** RegularExpression Id. */
  int _XSYMENDL = 136;
  /** RegularExpression Id. */
  int EXPATH = 137;
  /** RegularExpression Id. */
  int XSYMLINKPATH = 138;
  /** RegularExpression Id. */
  int INCLINE = 139;
  /** RegularExpression Id. */
  int MACEXPPATH = 140;
  /** RegularExpression Id. */
  int _COD = 141;
  /** RegularExpression Id. */
  int _WSP = 142;
  /** RegularExpression Id. */
  int __LT = 143;
  /** RegularExpression Id. */
  int _QTE = 144;
  /** RegularExpression Id. */
  int _ECMT_INC = 145;
  /** RegularExpression Id. */
  int _ECMT_INCLUDE_ns = 146;
  /** RegularExpression Id. */
  int _ECMT_INCLUDE_s = 147;
  /** RegularExpression Id. */
  int _ECMT_INCLUDE_es = 148;
  /** RegularExpression Id. */
  int _ECMT_INCLUDE_eo = 149;
  /** RegularExpression Id. */
  int _ECMT_INCLUDE_e = 150;
  /** RegularExpression Id. */
  int ESTD = 151;
  /** RegularExpression Id. */
  int STANDARD = 152;
  /** RegularExpression Id. */
  int _ENDREL = 153;
  /** RegularExpression Id. */
  int RELATIVE = 154;
  /** RegularExpression Id. */
  int PRAGMA_EXPRN = 155;
  /** RegularExpression Id. */
  int PRAGLINE = 156;
  /** RegularExpression Id. */
  int _LCMTPRAG = 157;
  /** RegularExpression Id. */
  int _SCMT_PRAG = 158;
  /** RegularExpression Id. */
  int _COD_WSP = 159;
  /** RegularExpression Id. */
  int _COD_PRAG = 160;
  /** RegularExpression Id. */
  int IFDEF_EXPRN = 161;
  /** RegularExpression Id. */
  int IFDLINE = 162;
  /** RegularExpression Id. */
  int _LCMT20 = 163;
  /** RegularExpression Id. */
  int _WSP3 = 164;
  /** RegularExpression Id. */
  int IFNDEF_EXPRN = 165;
  /** RegularExpression Id. */
  int IFNDLINE = 166;
  /** RegularExpression Id. */
  int _LCMT21 = 167;
  /** RegularExpression Id. */
  int _WSP4 = 168;
  /** RegularExpression Id. */
  int ERROR_EXPRN = 169;
  /** RegularExpression Id. */
  int ERRLINE = 170;
  /** RegularExpression Id. */
  int _WSP5 = 171;
  /** RegularExpression Id. */
  int WARNING_EXPRN = 172;
  /** RegularExpression Id. */
  int WARNLINE = 173;
  /** RegularExpression Id. */
  int _WSP6 = 174;
  /** RegularExpression Id. */
  int INFO_EXPRN = 175;
  /** RegularExpression Id. */
  int INFOLINE = 176;
  /** RegularExpression Id. */
  int _WSP_INFO = 177;
  /** RegularExpression Id. */
  int _LEADIN1 = 178;
  /** RegularExpression Id. */
  int CONSTITUENT = 179;
  /** RegularExpression Id. */
  int UNDLINE = 180;
  /** RegularExpression Id. */
  int _LEADIN2 = 181;
  /** RegularExpression Id. */
  int _WSP7 = 184;
  /** RegularExpression Id. */
  int _CODC = 185;
  /** RegularExpression Id. */
  int MANIFEST = 186;
  /** RegularExpression Id. */
  int CONLINE = 187;
  /** RegularExpression Id. */
  int LINLINE = 188;
  /** RegularExpression Id. */
  int LINEINFO = 189;
  /** RegularExpression Id. */
  int _ECMT_COMMENT_ns = 190;
  /** RegularExpression Id. */
  int _ECMT_COMMENT_s = 191;
  /** RegularExpression Id. */
  int _ECMT_COMMENT_es = 192;
  /** RegularExpression Id. */
  int _ECMT_COMMENT_eo = 193;
  /** RegularExpression Id. */
  int _ECMT_COMMENT_e = 194;
  /** RegularExpression Id. */
  int _CMT3 = 195;
  /** RegularExpression Id. */
  int _ECMT_DIRECTIVECOMMENT_ns = 196;
  /** RegularExpression Id. */
  int _ECMT_DIRECTIVECOMMENT_s = 197;
  /** RegularExpression Id. */
  int _ECMT_DIRECTIVECOMMENT_es = 198;
  /** RegularExpression Id. */
  int _ECMT_DIRECTIVECOMMENT_eo = 199;
  /** RegularExpression Id. */
  int _ECMT_DIRECTIVECOMMENT_e = 200;
  /** RegularExpression Id. */
  int _LCMT4 = 201;
  /** RegularExpression Id. */
  int _CMT4 = 202;
  /** RegularExpression Id. */
  int _QTE0 = 203;
  /** RegularExpression Id. */
  int _WSP8 = 204;
  /** RegularExpression Id. */
  int _COD2 = 205;
  /** RegularExpression Id. */
  int RVSLINE = 206;
  /** RegularExpression Id. */
  int VALUES = 207;
  /** RegularExpression Id. */
  int VALUESCMT = 208;
  /** RegularExpression Id. */
  int MOREVAL = 209;
  /** RegularExpression Id. */
  int _ECMT_RVALUES_ns = 210;
  /** RegularExpression Id. */
  int _ECMT_RVALUES_s = 211;
  /** RegularExpression Id. */
  int _ECMT_RVALUES_es = 212;
  /** RegularExpression Id. */
  int _ECMT_RVALUES_eo = 213;
  /** RegularExpression Id. */
  int _ECMT_RVALUES_e = 214;
  /** RegularExpression Id. */
  int _EQT = 215;
  /** RegularExpression Id. */
  int QUOTED_VALUE = 216;
  /** RegularExpression Id. */
  int MACROMV = 217;
  /** RegularExpression Id. */
  int MACROMVTAG = 218;
  /** RegularExpression Id. */
  int MACROARGSEND = 219;
  /** RegularExpression Id. */
  int _ECMT_MACROARGS = 220;
  /** RegularExpression Id. */
  int _CMT_MACROARGS = 221;
  /** RegularExpression Id. */
  int _MWSP = 222;
  /** RegularExpression Id. */
  int _COD3 = 223;
  /** RegularExpression Id. */
  int _MACWSP = 224;
  /** RegularExpression Id. */
  int _ECMT_MACROARGSns = 225;
  /** RegularExpression Id. */
  int _ECMT_MACROARGSs = 226;
  /** RegularExpression Id. */
  int _ECMT_MACROARGSes = 227;
  /** RegularExpression Id. */
  int _ECMT_MACROARGSeo = 228;
  /** RegularExpression Id. */
  int _ECMT_MACROARGSe = 229;
  /** RegularExpression Id. */
  int MOREARG = 231;
  /** RegularExpression Id. */
  int MACRORV = 232;
  /** RegularExpression Id. */
  int MACRORVCMT = 233;
  /** RegularExpression Id. */
  int _LCMT7 = 234;
  /** RegularExpression Id. */
  int _COD4 = 235;
  /** RegularExpression Id. */
  int _ECMT8 = 236;
  /** RegularExpression Id. */
  int _QTE1 = 237;
  /** RegularExpression Id. */
  int MCVLINE = 238;
  /** RegularExpression Id. */
  int LEADIN3 = 239;
  /** RegularExpression Id. */
  int _EQT1 = 240;
  /** RegularExpression Id. */
  int MQUOTED_VALUE = 241;
  /** RegularExpression Id. */
  int _ECMT_MACROVALS_ns = 242;
  /** RegularExpression Id. */
  int _ECMT_MACROVALS_s = 243;
  /** RegularExpression Id. */
  int _ECMT_MACROVALS_es = 244;
  /** RegularExpression Id. */
  int _ECMT_MACROVALS_eo = 245;
  /** RegularExpression Id. */
  int _ECMT_MACROVALS_e = 246;
  /** RegularExpression Id. */
  int _ECMT_MACROVALS_ew = 247;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int SpecialEOLComment = 1;
  /** Lexical state. */
  int SpecialBlockComment = 2;
  /** Lexical state. */
  int DIRECTIVE = 3;
  /** Lexical state. */
  int IGNORETOEOL = 4;
  /** Lexical state. */
  int INCDEF = 5;
  /** Lexical state. */
  int XSYMLINK = 6;
  /** Lexical state. */
  int XSYMPATH = 7;
  /** Lexical state. */
  int INCLUDE = 8;
  /** Lexical state. */
  int INCLUDE_COMMENT = 9;
  /** Lexical state. */
  int INCLUDE_COMMENT_END = 10;
  /** Lexical state. */
  int STDPATH = 11;
  /** Lexical state. */
  int RELPATH = 12;
  /** Lexical state. */
  int PRAGMA = 13;
  /** Lexical state. */
  int IFDEF = 14;
  /** Lexical state. */
  int IFNDEF = 15;
  /** Lexical state. */
  int ERROR = 16;
  /** Lexical state. */
  int WARNING = 17;
  /** Lexical state. */
  int INFO = 18;
  /** Lexical state. */
  int UNDEFINE = 19;
  /** Lexical state. */
  int DEFINE = 20;
  /** Lexical state. */
  int CONSTANT = 21;
  /** Lexical state. */
  int LINE = 22;
  /** Lexical state. */
  int COMMENT = 23;
  /** Lexical state. */
  int COMMENT_END = 24;
  /** Lexical state. */
  int LINECOMMENT = 25;
  /** Lexical state. */
  int DIRECTIVECOMMENT = 26;
  /** Lexical state. */
  int DIRECTIVECOMMENT_END = 27;
  /** Lexical state. */
  int RVALUES = 28;
  /** Lexical state. */
  int RVALUES_COMMENT = 29;
  /** Lexical state. */
  int RVALUES_COMMENT_END = 30;
  /** Lexical state. */
  int QUOTED_VAL = 31;
  /** Lexical state. */
  int MACROARGS = 32;
  /** Lexical state. */
  int MACROARGSCOMMENT = 33;
  /** Lexical state. */
  int MACROARGSCOMMENT_END = 34;
  /** Lexical state. */
  int CONTARG = 35;
  /** Lexical state. */
  int MACROVALS = 36;
  /** Lexical state. */
  int MQUOTED_VAL = 37;
  /** Lexical state. */
  int MACROVALS_COMMENT = 38;
  /** Lexical state. */
  int MACROVALS_COMMENT_END = 39;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\ufeff\"",
    "<_CTRL>",
    "<_XSYM>",
    "<_BLANKLINE>",
    "<_LCMT>",
    "<_CMT>",
    "<EOLCMNTNL>",
    "<token of kind 8>",
    "<CMNTNL>",
    "<token of kind 10>",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"||\"",
    "\"<<\"",
    "\">>\"",
    "\"-\"",
    "\"%\"",
    "\"+\"",
    "\"?\"",
    "\":\"",
    "\"#\"",
    "\"XSym\"",
    "\"/\"",
    "\"*\"",
    "\"*/\"",
    "\"/*\"",
    "<COD>",
    "<ENDL>",
    "<UNDIR>",
    "<UNDIRALL>",
    "\"defined\"",
    "\"__option\"",
    "\"\\\"\"",
    "\")\"",
    "\"(\"",
    "<NOPAR>",
    "<WSP>",
    "<STD>",
    "<REL>",
    "<NOTENDL>",
    "<NOTENDLC>",
    "<NOTENDLSTAR>",
    "<NOTCMT>",
    "<NOTCMTCOD>",
    "<NOTWS>",
    "<NOTWSQ>",
    "<NOTWQC>",
    "<NOTWWSQLT>",
    "<NOTWSQLT>",
    "\"/##/\"",
    "<INTEGER_LITERAL>",
    "<CHAR_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<HEX_DIGIT>",
    "<OCTAL_LITERAL>",
    "<FP_LITERAL>",
    "<EXPONENT>",
    "\"!\"",
    "<WS>",
    "<OUTER_TEXT>",
    "<NEWLINE>",
    "<OTHER_TEXT>",
    "<QUOTED_TEXT>",
    "\"include\"",
    "\"import\"",
    "\"include_next\"",
    "\"pragma\"",
    "\"error\"",
    "\"warning\"",
    "\"info\"",
    "\"define\"",
    "\"undef\"",
    "\"line\"",
    "<_WSP0>",
    "<_COD1>",
    "<_WSP2>",
    "\",\"",
    "<_LCMT0>",
    "<_CMT0>",
    "\"if\"",
    "\"elif\"",
    "\"else\"",
    "\"endif\"",
    "\"ifdef\"",
    "\"ifndef\"",
    "<NOT>",
    "<DEFINED>",
    "\"__has_include\"",
    "\"__has_include_next\"",
    "<OPTIONED>",
    "<EQ>",
    "<NEQ>",
    "<LT>",
    "<GT>",
    "<LE>",
    "<GE>",
    "<AND>",
    "<OR>",
    "<XOR>",
    "<LOG_OR>",
    "<LOG_AND>",
    "<LSH>",
    "<RSH>",
    "<MINUS>",
    "<PLUS>",
    "<DIVIDE>",
    "<MOD>",
    "<TIMES>",
    "<QMARK>",
    "<COLON>",
    "<NUMERIC>",
    "<FP_NUMERIC>",
    "<CHAR_NUMERIC>",
    "<ITEM>",
    "<BEGITEM>",
    "<ENDITEM>",
    "<DIRLINE>",
    "<_TOEOL>",
    "<_LCMT11>",
    "<_CMT11>",
    "<_INCCOD>",
    "<_INCWSP>",
    "<_INCCP>",
    "<_INCOP>",
    "<_INCSTANDARD>",
    "<_HEX>",
    "<_XSYMENDL>",
    "<EXPATH>",
    "<XSYMLINKPATH>",
    "<INCLINE>",
    "<MACEXPPATH>",
    "<_COD>",
    "<_WSP>",
    "<__LT>",
    "<_QTE>",
    "<_ECMT_INC>",
    "<_ECMT_INCLUDE_ns>",
    "\"*\"",
    "\"*\"",
    "<_ECMT_INCLUDE_eo>",
    "\"/\"",
    "<ESTD>",
    "<STANDARD>",
    "<_ENDREL>",
    "<RELATIVE>",
    "<PRAGMA_EXPRN>",
    "<PRAGLINE>",
    "<_LCMTPRAG>",
    "<_SCMT_PRAG>",
    "<_COD_WSP>",
    "<_COD_PRAG>",
    "<IFDEF_EXPRN>",
    "<IFDLINE>",
    "<_LCMT20>",
    "<_WSP3>",
    "<IFNDEF_EXPRN>",
    "<IFNDLINE>",
    "<_LCMT21>",
    "<_WSP4>",
    "<ERROR_EXPRN>",
    "<ERRLINE>",
    "<_WSP5>",
    "<WARNING_EXPRN>",
    "<WARNLINE>",
    "<_WSP6>",
    "<INFO_EXPRN>",
    "<INFOLINE>",
    "<_WSP_INFO>",
    "<_LEADIN1>",
    "<CONSTITUENT>",
    "<UNDLINE>",
    "<_LEADIN2>",
    "\"(\"",
    "\")\"",
    "<_WSP7>",
    "<_CODC>",
    "<MANIFEST>",
    "<CONLINE>",
    "<LINLINE>",
    "<LINEINFO>",
    "<_ECMT_COMMENT_ns>",
    "\"*\"",
    "\"*\"",
    "<_ECMT_COMMENT_eo>",
    "\"/\"",
    "<_CMT3>",
    "<_ECMT_DIRECTIVECOMMENT_ns>",
    "\"*\"",
    "\"*\"",
    "<_ECMT_DIRECTIVECOMMENT_eo>",
    "\"/\"",
    "<_LCMT4>",
    "<_CMT4>",
    "<_QTE0>",
    "<_WSP8>",
    "<_COD2>",
    "<RVSLINE>",
    "<VALUES>",
    "<VALUESCMT>",
    "<MOREVAL>",
    "<_ECMT_RVALUES_ns>",
    "\"*\"",
    "\"*\"",
    "<_ECMT_RVALUES_eo>",
    "\"/\"",
    "<_EQT>",
    "<QUOTED_VALUE>",
    "<MACROMV>",
    "<MACROMVTAG>",
    "\")\"",
    "<_ECMT_MACROARGS>",
    "<_CMT_MACROARGS>",
    "\",\"",
    "<_COD3>",
    "<_MACWSP>",
    "<_ECMT_MACROARGSns>",
    "\"*\"",
    "\"*\"",
    "<_ECMT_MACROARGSeo>",
    "\"/\"",
    "\")\"",
    "<MOREARG>",
    "<MACRORV>",
    "<MACRORVCMT>",
    "<_LCMT7>",
    "<_COD4>",
    "<_ECMT8>",
    "<_QTE1>",
    "<MCVLINE>",
    "<LEADIN3>",
    "<_EQT1>",
    "<MQUOTED_VALUE>",
    "<_ECMT_MACROVALS_ns>",
    "\"*\"",
    "\"*\"",
    "<_ECMT_MACROVALS_eo>",
    "\"/\"",
    "<_ECMT_MACROVALS_ew>",
  };

}
